AppBundle\Entity\User:
  type: entity
  table: app_users
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 25
      unique: true
    password:
      type: string
      length: 64
    email:
      type: string
      length: 60
      unique: true
    is_active:
      type: boolean
  manyToMany:
    lessons:
      targetEntity: Lesson
      inversedBy: users
      joinTable:
        name: users_lessons
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          lesson_id:
            referencedColumnName: id
