<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
	/**
	 * @param string $level_slug
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getLessonsByLevel($level_slug)
	{
		$em = $this->getEntityManager();
		$level = $em->getRepository('AppBundle:Level')
			->findOneBy(['slug' => $level_slug]);

		if (!$level) {
			throw new NotFoundHttpException('Level not found');
		}

		return $level->getLessons();
	}

	/**
	 * @param string $level_slug
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getTopLessonsByLevel($level_slug)
	{
		$qb = $this
			->createQueryBuilder('l')
			->select('l')
			->addSelect('COUNT(u.id) AS HIDDEN nb_users')
			->leftJoin('l.users', 'u')
			->innerJoin('l.level', 'le')
			->where('le.slug = :level_slug')
			->setParameter('level_slug', $level_slug)
			->groupBy('l.id')
			->addOrderBy('nb_users', 'DESC')
			->setMaxResults(6);


		return $qb->getQuery()->getResult();
	}
}
